import { Share, Platform, NativeModules, TurboModuleRegistry } from 'react-native';
import { DocumentEvaluationResult } from './calcNoteEngine';
import { showInterstitialAd } from './adMobService';

export type ExportDocumentData = {
  title: string;
  evaluation: DocumentEvaluationResult;
  themePrimaryColor?: string;
  themeAccentColor?: string;
  isDarkMode?: boolean;
};

export type ExportResult = {
  success: boolean;
  message: string;
};

// Safe native module detector: checks registries without invoking throwing getters
export const isNativeModuleAvailable = (moduleName: string): boolean => {
  if (Platform.OS === 'web') return false;
  try {
    const globalObj = typeof globalThis !== 'undefined' ? (globalThis as any) : (global as any);
    // Check ExpoModules / expo.modules registry
    if (globalObj?.expo?.modules?.[moduleName]) return true;
    if (globalObj?.ExpoModules?.[moduleName]) return true;
    if (globalObj?.NativeModulesProxy?.[moduleName]) return true;
    // Check NativeModules
    if (NativeModules && NativeModules[moduleName]) return true;
    return false;
  } catch {
    return false;
  }
};

export const isViewShotAvailable = (): boolean => {
  if (Platform.OS === 'web') return false;
  try {
    if (TurboModuleRegistry && typeof TurboModuleRegistry.get === 'function') {
      return TurboModuleRegistry.get('RNViewShot') != null;
    }
    return (NativeModules && NativeModules['RNViewShot']) != null;
  } catch {
    return false;
  }
};

export const isPrintAvailable = (): boolean => {
  return isNativeModuleAvailable('ExpoPrint');
};

export const isSharingAvailable = (): boolean => {
  return isNativeModuleAvailable('ExpoSharing');
};

const getPrintModule = () => {
  if (!isPrintAvailable()) return null;
  try {
    return require('expo-print');
  } catch (e) {
    return null;
  }
};

const getSharingModule = () => {
  if (!isSharingAvailable()) return null;
  try {
    return require('expo-sharing');
  } catch (e) {
    return null;
  }
};

const getViewShotModule = () => {
  if (!isViewShotAvailable()) return null;
  try {
    return require('react-native-view-shot');
  } catch (e) {
    return null;
  }
};

/**
 * Formats a clean, proportional ASCII text receipt for sharing across messaging apps
 */
export const formatReceiptText = (data: ExportDocumentData): string => {
  const { title, evaluation } = data;
  const dateStr = new Date().toLocaleString();
  const divider = '==========================================';
  const dashed = '------------------------------------------';

  const rows = evaluation.lines
    .filter((l) => !l.isComment || l.rawText.trim().length > 0)
    .map((l) => {
      const num = String(l.lineNumber).padStart(2, ' ');
      if (l.isComment) {
        return ` ${num} | ${l.rawText}`;
      }
      const text = (l.rawText || '').padEnd(24, ' ').slice(0, 24);
      const res = (l.resultText || '').padStart(12, ' ');
      return ` ${num} | ${text} | ${res}`;
    });

  return [
    divider,
    `         CALCNOTE EVOLUTION RECEIPT       `,
    `  ${(title || 'CALCULATION SHEET').toUpperCase()}`,
    `  Date: ${dateStr}`,
    divider,
    ` LN | ITEM / FORMULA            | AMOUNT     `,
    dashed,
    ...rows,
    divider,
    ` TOTAL (NET BALANCE): ${evaluation.formattedGrandTotal.padStart(20, ' ')}`,
    divider,
    ` Verified • ${evaluation.solvedCount} calculated lines`,
    ` Generated by NoteCalc Pro`,
    divider,
  ].join('\n');
};

/**
 * Compiles a printable HTML template for PDF generation and browser printing
 */
export const generateCalcNoteHtml = (data: ExportDocumentData): string => {
  const { title, evaluation, themeAccentColor = '#00F2FE' } = data;
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });

  const rowsHtml = evaluation.lines
    .map((line) => {
      const isComment = line.isComment;
      const isError = line.hasError;
      const rawTextEscaped = (line.rawText || '')
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');

      return `
        <tr class="${isComment ? 'comment-row' : ''} ${isError ? 'error-row' : ''}">
          <td class="line-num">${line.lineNumber}</td>
          <td class="line-text">${rawTextEscaped || '&nbsp;'}</td>
          <td class="line-result ${isError ? 'result-error' : ''}">
            ${line.resultText ? line.resultText : ''}
          </td>
        </tr>
      `;
    })
    .join('');

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>${title || 'CalcNote Calculation'}</title>
        <style>
          * {
            box-sizing: border-box;
            margin: 0;
            padding: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
          }
          body {
            background-color: #ffffff;
            color: #0f172a;
            padding: 40px;
            max-width: 800px;
            margin: 0 auto;
          }
          .header {
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            border-bottom: 2px solid #e2e8f0;
            padding-bottom: 20px;
            margin-bottom: 24px;
          }
          .logo-badge {
            background: linear-gradient(135deg, ${themeAccentColor}, #0284c7);
            color: #ffffff;
            font-weight: 800;
            font-size: 13px;
            padding: 6px 14px;
            border-radius: 8px;
            display: inline-block;
            margin-bottom: 8px;
            letter-spacing: 1px;
          }
          .doc-title {
            font-size: 24px;
            font-weight: 700;
            color: #0f172a;
          }
          .meta-info {
            text-align: right;
            font-size: 12px;
            color: #64748b;
          }
          .meta-info span {
            display: block;
            margin-top: 4px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin-bottom: 24px;
          }
          th {
            text-align: left;
            padding: 10px 12px;
            background-color: #f8fafc;
            border-bottom: 2px solid #cbd5e1;
            font-size: 11px;
            font-weight: 700;
            text-transform: uppercase;
            letter-spacing: 0.8px;
            color: #475569;
          }
          td {
            padding: 9px 12px;
            border-bottom: 1px solid #f1f5f9;
            font-size: 14px;
            vertical-align: middle;
          }
          .line-num {
            width: 48px;
            color: #94a3b8;
            font-family: monospace;
            font-size: 12px;
          }
          .line-text {
            color: #1e293b;
            font-weight: 500;
          }
          .line-result {
            width: 180px;
            text-align: right;
            font-weight: 700;
            color: #0284c7;
            font-family: monospace;
            font-size: 15px;
          }
          .comment-row td {
            color: #94a3b8;
            font-style: italic;
          }
          .error-row .line-result {
            color: #ef4444;
          }
          .summary-card {
            background-color: #f8fafc;
            border: 1px solid #e2e8f0;
            border-radius: 12px;
            padding: 18px 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-top: 16px;
          }
          .summary-label {
            font-size: 13px;
            font-weight: 600;
            color: #475569;
            text-transform: uppercase;
            letter-spacing: 0.8px;
          }
          .summary-value {
            font-size: 24px;
            font-weight: 800;
            color: #0f172a;
            font-family: monospace;
          }
          .footer {
            margin-top: 36px;
            border-top: 1px solid #e2e8f0;
            padding-top: 16px;
            text-align: center;
            font-size: 11px;
            color: #94a3b8;
          }
          @media print {
            body {
              padding: 0;
            }
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <div class="logo-badge">CALCNOTE EVOLUTION</div>
            <h1 class="doc-title">${title || 'Untitled Calculation Sheet'}</h1>
          </div>
          <div class="meta-info">
            <span>Date: ${dateStr}</span>
            <span>Total Lines: ${evaluation.lineCount}</span>
            <span>Solved: ${evaluation.solvedCount}</span>
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th>#</th>
              <th>Equation / Description</th>
              <th style="text-align: right;">Result</th>
            </tr>
          </thead>
          <tbody>
            ${rowsHtml}
          </tbody>
        </table>

        <div class="summary-card">
          <div class="summary-label">Grand Total (Net Balance)</div>
          <div class="summary-value">${evaluation.formattedGrandTotal}</div>
        </div>

        <div class="footer">
          Compiled with CalcNote Evolution • High-Performance Reactive Notepad Calculator
        </div>
      </body>
    </html>
  `;
};

/**
 * Web-specific PDF generation using native browser print dialog
 */
export const generateWebPdf = async (data: ExportDocumentData): Promise<boolean> => {
  if (typeof window === 'undefined' || typeof document === 'undefined') return false;

  const html = generateCalcNoteHtml(data);

  return new Promise((resolve) => {
    try {
      const iframe = document.createElement('iframe');
      iframe.style.position = 'fixed';
      iframe.style.right = '0';
      iframe.style.bottom = '0';
      iframe.style.width = '0';
      iframe.style.height = '0';
      iframe.style.border = '0';
      document.body.appendChild(iframe);

      const doc = iframe.contentWindow?.document;
      if (doc) {
        doc.open();
        doc.write(html);
        doc.close();

        setTimeout(() => {
          try {
            iframe.contentWindow?.focus();
            iframe.contentWindow?.print();
            resolve(true);
          } catch (e) {
            const win = window.open('', '_blank');
            if (win) {
              win.document.write(html);
              win.document.close();
              win.focus();
              win.print();
              resolve(true);
            } else {
              resolve(false);
            }
          } finally {
            setTimeout(() => {
              if (document.body.contains(iframe)) {
                document.body.removeChild(iframe);
              }
            }, 30000);
          }
        }, 250);
      } else {
        resolve(false);
      }
    } catch (err) {
      console.warn('Web PDF export failed:', err);
      resolve(false);
    }
  });
};

/**
 * Web-specific high-resolution PNG receipt renderer via HTML5 Canvas
 */
export const generateWebReceiptPng = async (data: ExportDocumentData): Promise<boolean> => {
  if (typeof document === 'undefined') return false;

  const { title, evaluation, themeAccentColor = '#00F2FE' } = data;
  const lines = evaluation.lines.filter((l) => !l.isComment || l.rawText.trim().length > 0);

  const rowHeight = 36;
  const headerHeight = 140;
  const footerHeight = 110;
  const padding = 32;
  const width = 640;
  const height = Math.max(headerHeight + lines.length * rowHeight + footerHeight + padding * 2, 400);

  const canvas = document.createElement('canvas');
  const dpr = 2; // 2x Retina Resolution
  canvas.width = width * dpr;
  canvas.height = height * dpr;
  const ctx = canvas.getContext('2d');
  if (!ctx) return false;

  ctx.scale(dpr, dpr);

  // Background OLED card
  ctx.fillStyle = '#0B0F19';
  ctx.fillRect(0, 0, width, height);

  // Outer border
  ctx.strokeStyle = '#1E293B';
  ctx.lineWidth = 2;
  ctx.strokeRect(1, 1, width - 2, height - 2);

  // Top header badge
  ctx.fillStyle = themeAccentColor;
  ctx.font = 'bold 11px system-ui, -apple-system, sans-serif';
  ctx.fillText('CALCNOTE EVOLUTION • SMART RECEIPT', padding, padding + 16);

  // Document Title
  ctx.fillStyle = '#FFFFFF';
  ctx.font = 'bold 22px system-ui, -apple-system, sans-serif';
  ctx.fillText(title || 'Calculation Summary', padding, padding + 46);

  // Date & stats
  ctx.fillStyle = '#64748B';
  ctx.font = '12px system-ui, -apple-system, sans-serif';
  const dateStr = new Date().toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'short',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
  ctx.fillText(`${dateStr}  •  ${evaluation.solvedCount} calculated lines`, padding, padding + 70);

  // Separator line
  ctx.strokeStyle = '#1E293B';
  ctx.beginPath();
  ctx.moveTo(padding, padding + 88);
  ctx.lineTo(width - padding, padding + 88);
  ctx.stroke();

  // Headers
  const tableStartY = padding + 110;
  ctx.fillStyle = '#475569';
  ctx.font = 'bold 11px system-ui, -apple-system, sans-serif';
  ctx.fillText('#', padding, tableStartY);
  ctx.fillText('EQUATION / TEXT', padding + 36, tableStartY);
  ctx.textAlign = 'right';
  ctx.fillText('RESULT', width - padding, tableStartY);
  ctx.textAlign = 'left';

  // Rows
  let curY = tableStartY + 24;
  lines.forEach((l, i) => {
    if (i % 2 === 0) {
      ctx.fillStyle = 'rgba(255, 255, 255, 0.02)';
      ctx.fillRect(padding - 8, curY - 18, width - padding * 2 + 16, rowHeight);
    }

    ctx.fillStyle = '#475569';
    ctx.font = '12px monospace';
    ctx.fillText(`${l.lineNumber}`, padding, curY);

    ctx.fillStyle = l.isComment ? '#64748B' : '#E2E8F0';
    ctx.font = l.isComment ? 'italic 13px system-ui, sans-serif' : '14px system-ui, sans-serif';
    const truncatedText = l.rawText.length > 40 ? l.rawText.slice(0, 38) + '…' : l.rawText;
    ctx.fillText(truncatedText || '—', padding + 36, curY);

    if (l.resultText) {
      ctx.textAlign = 'right';
      ctx.fillStyle = l.hasError ? '#FF4757' : themeAccentColor;
      ctx.font = 'bold 14px monospace';
      ctx.fillText(l.resultText, width - padding, curY);
      ctx.textAlign = 'left';
    }

    curY += rowHeight;
  });

  // Grand Total Box
  curY += 12;
  ctx.fillStyle = 'rgba(0, 242, 254, 0.08)';
  ctx.strokeStyle = 'rgba(0, 242, 254, 0.35)';
  ctx.lineWidth = 1;
  const boxHeight = 56;
  ctx.fillRect(padding, curY, width - padding * 2, boxHeight);
  ctx.strokeRect(padding, curY, width - padding * 2, boxHeight);

  ctx.fillStyle = '#94A3B8';
  ctx.font = 'bold 12px system-ui, sans-serif';
  ctx.fillText('GRAND TOTAL (NET BALANCE)', padding + 16, curY + 34);

  ctx.textAlign = 'right';
  ctx.fillStyle = '#FFFFFF';
  ctx.font = 'bold 20px monospace';
  ctx.fillText(evaluation.formattedGrandTotal, width - padding - 16, curY + 36);
  ctx.textAlign = 'left';

  // Footer branding
  curY += boxHeight + 24;
  ctx.fillStyle = '#475569';
  ctx.font = '11px system-ui, sans-serif';
  ctx.textAlign = 'center';
  ctx.fillText('Exported from NoteCalc Pro • Smart Notepad & Calculator', width / 2, curY);

  return new Promise((resolve) => {
    canvas.toBlob((blob) => {
      if (!blob) {
        resolve(false);
        return;
      }
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      const cleanName = (title || 'Calculation').replace(/[^a-z0-9]/gi, '_').toLowerCase();
      a.download = `${cleanName}_receipt.png`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 2000);
      resolve(true);
    }, 'image/png');
  });
};

/**
 * Universal PDF Export
 */
export const exportNoteAsPdf = async (data: ExportDocumentData): Promise<ExportResult> => {
  try {
    // 1. Web: Native print dialog
    if (Platform.OS === 'web') {
      const ok = await generateWebPdf(data);
      if (ok) {
        return { success: true, message: 'Print dialog opened! Choose "Save as PDF" to save.' };
      }
    }

    // 2. Native: expo-print if registered
    const Print = getPrintModule();
    const Sharing = getSharingModule();

    if (Print && typeof Print.printToFileAsync === 'function') {
      try {
        const html = generateCalcNoteHtml(data);
        const { uri } = await Print.printToFileAsync({
          html,
          base64: false,
        });

        if (Sharing && typeof Sharing.isAvailableAsync === 'function' && (await Sharing.isAvailableAsync())) {
          await Sharing.shareAsync(uri, {
            UTI: '.pdf',
            mimeType: 'application/pdf',
            dialogTitle: `Share ${data.title || 'Calculation Note'}`,
          });
          showInterstitialAd();
          return { success: true, message: 'PDF document generated and shared!' };
        } else {
          await Share.share({
            title: data.title,
            url: uri,
          });
          showInterstitialAd();
          return { success: true, message: 'PDF document exported!' };
        }
      } catch (nativePrintErr) {
        console.warn('Native Print error:', nativePrintErr);
      }
    }

    // Return preview_only so the in-app document sheet is presented without unwanted text share dialog
    return { success: false, message: 'preview_only' };
  } catch (error: any) {
    console.warn('PDF export fallback:', error);
    return { success: false, message: 'preview_only' };
  }
};

/**
 * Universal PNG Receipt Export
 */
export const exportNoteAsImage = async (
  viewRef: any,
  data: ExportDocumentData
): Promise<ExportResult> => {
  try {
    // 1. Web: 2x Canvas download
    if (Platform.OS === 'web') {
      const ok = await generateWebReceiptPng(data);
      if (ok) {
        return { success: true, message: 'PNG receipt downloaded to your files!' };
      }
    }

    // 2. Native: react-native-view-shot if registered
    const viewShot = getViewShotModule();
    const Sharing = getSharingModule();
    const captureRef = viewShot?.captureRef;

    if (viewRef && viewRef.current && captureRef) {
      try {
        const uri = await captureRef(viewRef, {
          format: 'png',
          quality: 1,
          result: 'tmpfile',
        });

        if (Sharing && typeof Sharing.isAvailableAsync === 'function' && (await Sharing.isAvailableAsync())) {
          await Sharing.shareAsync(uri, {
            UTI: '.png',
            mimeType: 'image/png',
            dialogTitle: `Share ${data.title || 'Calculation Note'} Receipt`,
          });
          showInterstitialAd();
          return { success: true, message: 'Visual PNG receipt shared!' };
        } else {
          await Share.share({
            title: data.title,
            url: uri,
          });
          showInterstitialAd();
          return { success: true, message: 'Visual PNG receipt exported!' };
        }
      } catch (viewShotErr) {
        console.warn('Native view-shot error:', viewShotErr);
      }
    }

    // If native snapshot is unavailable, return false so the in-app digital receipt preview displays smoothly
    return { success: false, message: 'Digital receipt card ready to view and share.' };
  } catch (error) {
    console.warn('Image export error:', error);
    return { success: false, message: 'Digital receipt card ready.' };
  }
};

/**
 * Universal Plain Text / Markdown Export
 */
export const exportNoteAsText = async (data: ExportDocumentData): Promise<ExportResult> => {
  try {
    const lines = data.evaluation.lines.map((l) => {
      if (l.isComment) return l.rawText;
      return `${(l.rawText || '').padEnd(30, ' ')} = ${l.resultText || ''}`;
    });

    const body = [
      `# ${data.title || 'CalcNote Calculation'}`,
      `Date: ${new Date().toLocaleString()}`,
      `-----------------------------------------`,
      ...lines,
      `-----------------------------------------`,
      `GRAND TOTAL: ${data.evaluation.formattedGrandTotal}`,
    ].join('\n');

    if (Platform.OS === 'web' && typeof navigator !== 'undefined' && navigator.clipboard) {
      await navigator.clipboard.writeText(body);
      return { success: true, message: 'Calculation sheet copied to clipboard!' };
    }

    await Share.share({
      title: data.title,
      message: body,
    });
    return { success: true, message: 'Calculation sheet shared!' };
  } catch (error) {
    console.error('Text export error:', error);
    return { success: false, message: 'Could not export text.' };
  }
};
